<div class="field test_address_counter_rooms">
    <label class="label" for="test_address_counter_rooms">
        <span><?= $block->escapeHtml(__('Counter Rooms')) ?></span>
    </label>
    <div class="control">
        <input type="text" name="test_address_counter_rooms" id="test_address_counter_rooms" value="" title="<?= $block->escapeHtmlAttr(__('Counter Rooms')) ?>" class="input-text" data-validate="{required:true}">
    </div>
</div>
