<?php /** @var ArseniyInk\TaskTwo\Block\Customer\Widget\Count $block */ ?>
<div class="field count <?php if ($block->isRequired()) echo ' required'; ?> ">
    <label class="label" for="<?php echo $block->escapeHtml($block->getFieldId()); ?>">
        <span><?php echo $block->escapeHtml($block->getFieldLabel()); ?></span>
    </label>
    <div class="control">
        <input type="text"
               id="<?php echo $block->escapeHtml($block->getFieldId()); ?>"
               name="<?php echo $block->escapeHtml($block->getFieldName()); ?>"
               value="<?php echo $block->escapeHtml($block->getValue()); ?>"
               title="<?php echo $block->escapeHtml($block->getFieldLabel()); ?>"
               class="input-text"
               <?php /*escapeNotVerified */ echo $block->getFieldParams() ?>
               <?php if ($block->isRequired()) echo ' data-validate="{required:true}"' ?> />
    </div>
</div>
